# Generated by Django 2.2.6 on 2019-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
