# Generated by Django 2.2.6 on 2019-10-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_newreportdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newreportdata',
            old_name='h_image',
            new_name='image',
        ),
    ]
