# Generated by Django 2.2.6 on 2019-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20191004_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newreportdata',
            old_name='h_location',
            new_name='h_latitude',
        ),
        migrations.AddField(
            model_name='newreportdata',
            name='h_longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
